### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by ofek** [volos/HackerNewsUX#2]
Are there plans to implement infinite scrolling like the Reddit Enhancement Suite?

**Comment by volos** [comment]
Thanks for your interest. 

You are welcome to clone the repository, and add a feature to detect when the end of the page has been reached, and invoke the code that exists already in the script, and is bound as a button, which dynamically loads/appends the next-page, for each column.

Should you add such feature, please make it so, that someone can also disable it easily, and there is a timer, so, that someone can reach, without any frustration, the links in the end of the page.

If it is user-friendly, I will be happy to publish it as an update in the main version.

**Comment by ofek** [comment]
Implemented?
